#logging.level: debug

filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.labels.nodetype: "application"
          config:
            - type: docker
              containers.ids:
                - "${data.docker.container.id}"
              encoding: utf-8
              stream: "stdout"

output.logstash:
  hosts: ["logstash:5044"]